version: '3.2'

services:
  library_db:
    image: mdillon/postgis:11
    restart: always
    container_name: biblioteca-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    expose:
      - 5432
    ports:
      - 5430:5432
    networks:
      - app      

  app:
    build: 
      context: library_back
      dockerfile: Dockerfile
    container_name: biblioteca-api
    ports: 
     - "8000:8000"
    command: bash -c "
      sleep 15 &&
      python /app/manage.py makemigrations && 
      python /app/manage.py migrate && 
      python /app/manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
      - POSTGRES_HOST=library_db
      - POSTGRES_PORT=5432
    depends_on:
      - library_db
    networks:
      - app
  
  app_front:
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app
      - library_db
    networks:
      - app

networks:
      app:
        driver: bridge